/**
 * Modellregiszter: ismert modellek metaadatai + lekérdező helperök.
 *
 * Konvenciók:
 * - WebLLM modellek: `modelUrl` a HuggingFace `.../resolve/main/` végpontra mutat,
 *   ez kerül a WebLLM `appConfig.model_list` bejegyzés `model` mezőjébe.
 * - transformers.js modellek: `hfRepo` a Hub repo azonosító, a súlyok
 *   betöltése az AudioModule/PipelineModule-ben történik (lazy).
 * - `sizeMB` / `vramMB` közelítő értékek; UI kijelzésre és
 *   progress-becslésre szolgálnak, nem kvótakezelésre.
 * - Minden transformers `hfRepo` 200-as státusszal ellenőrzött a Hubon;
 *   zárt (401) repók nem szerepelnek a katalógusban.
 * - `score` tájékoztató adat a modellkártya/paper alapján, nem saját mérés.
 */

import type { ModelCategory, ModelInfo, ModelTask } from './types.js';

/** Alapértelmezett modell: legkisebb VRAM-igényű chat modell. */
export const DEFAULT_MODEL = 'qwen-2.5-0.5b';

/** Kategóriák stabil megjelenítési sorrendben (docs/models oldal). */
export const MODEL_CATEGORIES: ModelCategory[] = [
  'Chat',
  'Embedding & retrieval',
  'Classification',
  'Comprehension',
  'Generation',
  'Translation',
  'Vision',
  'Document',
  'Speech',
];

/** Ismert modellek szótára id → metaadat. */
export const MODEL_REGISTRY: Record<string, ModelInfo> = {
  // -- Chat (WebLLM, WebGPU) -------------------------------------------------
  'qwen-2.5-0.5b': {
    id: 'qwen-2.5-0.5b',
    label: 'Qwen2.5 0.5B Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 400,
    params: '0.5B',
    contextWindow: 4096,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 1400,
    description: 'Legkisebb Qwen chat modell; gyenge GPU-n / teszteléshez ajánlott.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'smollm2-135m': {
    id: 'smollm2-135m',
    label: 'SmolLM2 135M Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/SmolLM2-135M-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 150,
    params: '135M',
    contextWindow: 8192,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 1100,
    description: 'A katalógus legkisebb chat modellje; egyszerű kérdésekre, demóhoz elég.',
    evals: ['MMLU', 'ARC-c', 'HellaSwag'],
  },
  'smollm2-360m': {
    id: 'smollm2-360m',
    label: 'SmolLM2 360M Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 300,
    params: '360M',
    contextWindow: 8192,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 1500,
    description: 'Még 300 MB alatt, de érezhetően jobb instrukciókövetés, mint a 135M.',
    evals: ['MMLU', 'ARC-c', 'HellaSwag'],
  },
  'qwen-2.5-1.5b': {
    id: 'qwen-2.5-1.5b',
    label: 'Qwen2.5 1.5B Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Qwen2.5-1.5B-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 1100,
    params: '1.5B',
    contextWindow: 4096,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 2600,
    description: 'Jó minőség/méret arány általános csevegésre.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'qwen-2.5-3b': {
    id: 'qwen-2.5-3b',
    label: 'Qwen2.5 3B Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Qwen2.5-3B-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 2200,
    params: '3B',
    contextWindow: 4096,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 4200,
    description: 'Erősebb érvelés és tool-calling hajlam; 4 GB+ VRAM kell.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'llama-3.2-1b': {
    id: 'llama-3.2-1b',
    label: 'Llama 3.2 1B Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Llama-3.2-1B-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 900,
    params: '1B',
    contextWindow: 8192,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 2400,
    description: 'Meta Llama 3.2 kis modell; rövid instrukciókövetésre jó.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'llama-3.2-3b': {
    id: 'llama-3.2-3b',
    label: 'Llama 3.2 3B Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Llama-3.2-3B-Instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 2400,
    params: '3B',
    contextWindow: 8192,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 4400,
    description: 'Llama 3.2 nagyobb modell; összefoglalásra, RAG-ra alkalmas.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'phi-3.5-mini': {
    id: 'phi-3.5-mini',
    label: 'Phi-3.5-mini Instruct (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/Phi-3.5-mini-instruct-q4f16_1-MLC/resolve/main/',
    sizeMB: 2700,
    params: '3.8B',
    contextWindow: 4096,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 4800,
    description: 'Microsoft Phi kis modell; kód- és érvelési feladatokra erős.',
    evals: ['MMLU', 'HumanEval', 'ARC-c'],
  },
  'gemma-2-2b': {
    id: 'gemma-2-2b',
    label: 'Gemma 2 2B IT (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/gemma-2-2b-it-q4f16_1-MLC/resolve/main/',
    sizeMB: 1800,
    params: '2B',
    contextWindow: 8192,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 3600,
    description: 'Google Gemma 2; fegyelmezett instrukciókövetés.',
    evals: ['MMLU', 'HellaSwag', 'ARC-c'],
  },
  'deepseek-r1-distill-qwen-1.5b': {
    id: 'deepseek-r1-distill-qwen-1.5b',
    label: 'DeepSeek-R1-Distill-Qwen 1.5B (q4f16_1)',
    provider: 'webllm',
    modelUrl:
      'https://huggingface.co/mlc-ai/DeepSeek-R1-Distill-Qwen-1.5B-q4f16_1-MLC/resolve/main/',
    sizeMB: 1200,
    params: '1.5B',
    contextWindow: 4096,
    quantization: 'q4f16_1',
    task: 'chat',
    category: 'Chat',
    vramMB: 2800,
    description: 'Érvelésre desztillált modell; lépésenkénti gondolkodást ír ki.',
    evals: ['MMLU', 'GSM8K', 'ARC-c'],
  },

  // -- Embedding & retrieval (transformers.js, CPU) ---------------------------
  'embed-minilm-l6': {
    id: 'embed-minilm-l6',
    label: 'all-MiniLM-L6-v2 (embedding)',
    provider: 'transformers',
    hfRepo: 'Xenova/all-MiniLM-L6-v2',
    sizeMB: 80,
    params: '23M',
    contextWindow: 256,
    task: 'embedding',
    category: 'Embedding & retrieval',
    vramMB: 400,
    description: 'Alapértelmezett beágyazó: gyors, kicsi, RAG-hoz legtöbbször elég.',
    evals: ['MTEB', 'STS-B'],
  },
  'embed-minilm-l12': {
    id: 'embed-minilm-l12',
    label: 'all-MiniLM-L12-v2 (embedding)',
    provider: 'transformers',
    hfRepo: 'Xenova/all-MiniLM-L12-v2',
    sizeMB: 120,
    params: '33M',
    contextWindow: 256,
    task: 'embedding',
    category: 'Embedding & retrieval',
    vramMB: 500,
    description: 'Az L6 nagyobb testvére; kicsit pontosabb, még mindig könnyű.',
    evals: ['MTEB', 'STS-B'],
  },
  'embed-bge-small': {
    id: 'embed-bge-small',
    label: 'bge-small-en-v1.5 (embedding)',
    provider: 'transformers',
    hfRepo: 'Xenova/bge-small-en-v1.5',
    sizeMB: 130,
    params: '33M',
    contextWindow: 512,
    task: 'embedding',
    category: 'Embedding & retrieval',
    vramMB: 500,
    description: 'Erős retrieval-minőség; RAG-rangsoroláshoz jó választás.',
    evals: ['MTEB', 'BEIR'],
  },
  'embed-e5-small': {
    id: 'embed-e5-small',
    label: 'e5-small-v2 (embedding)',
    provider: 'transformers',
    hfRepo: 'Xenova/e5-small-v2',
    sizeMB: 130,
    params: '33M',
    contextWindow: 512,
    task: 'embedding',
    category: 'Embedding & retrieval',
    vramMB: 500,
    description: 'E5-család kicsi tagja; lekérdezéshez "query: " prefixet érdemes adni.',
    evals: ['MTEB', 'BEIR'],
  },
  'embed-gte-small': {
    id: 'embed-gte-small',
    label: 'gte-small (embedding)',
    provider: 'transformers',
    hfRepo: 'Xenova/gte-small',
    sizeMB: 130,
    params: '33M',
    contextWindow: 512,
    task: 'embedding',
    category: 'Embedding & retrieval',
    vramMB: 500,
    description: 'GTE-család kicsi modellje; hosszú szövegeket is kezel.',
    evals: ['MTEB'],
  },
  'rerank-minilm-l6': {
    id: 'rerank-minilm-l6',
    label: 'ms-marco-MiniLM-L-6-v2 (rerank)',
    provider: 'transformers',
    hfRepo: 'Xenova/ms-marco-MiniLM-L-6-v2',
    sizeMB: 90,
    params: '23M',
    contextWindow: 512,
    task: 'rerank',
    category: 'Embedding & retrieval',
    vramMB: 400,
    description: 'Cross-encoder újrarangsoroló: az embedding-találatok sorrendjét javítja.',
    evals: ['MS MARCO'],
    score: '~39 MRR@10',
  },

  // -- Classification (transformers.js, CPU) ----------------------------------
  'sentiment-distilbert': {
    id: 'sentiment-distilbert',
    label: 'DistilBERT SST-2 (sentiment)',
    provider: 'transformers',
    hfRepo: 'Xenova/distilbert-base-uncased-finetuned-sst-2-english',
    sizeMB: 260,
    params: '67M',
    contextWindow: 512,
    task: 'text-classification',
    category: 'Classification',
    vramMB: 600,
    description: 'Angol szentiment (pozitív/negatív) vélemény-stílusú szövegeken.',
    evals: ['SST-2'],
    score: '~91% pontosság',
  },
  'zeroshot-mobilebert-mnli': {
    id: 'zeroshot-mobilebert-mnli',
    label: 'MobileBERT MNLI (zero-shot)',
    provider: 'transformers',
    hfRepo: 'Xenova/mobilebert-uncased-mnli',
    sizeMB: 100,
    params: '25M',
    contextWindow: 512,
    task: 'zero-shot',
    category: 'Classification',
    vramMB: 400,
    description: 'Zero-shot osztályozás tetszőleges címkékkel, tanítás nélkül.',
    evals: ['MNLI'],
    score: '~84% (MNLI)',
  },

  // -- Comprehension: kérdésmegválaszolás -------------------------------------
  'qa-distilbert-squad': {
    id: 'qa-distilbert-squad',
    label: 'DistilBERT SQuAD (cased)',
    provider: 'transformers',
    hfRepo: 'Xenova/distilbert-base-cased-distilled-squad',
    sizeMB: 260,
    params: '67M',
    contextWindow: 512,
    task: 'qa',
    category: 'Comprehension',
    vramMB: 600,
    description: 'Kérdésmegválaszolás megadott kontextusból (angol, kis-nagybetű érzékeny).',
    evals: ['SQuAD v1.1'],
    score: '~87 F1',
  },
  'qa-distilbert-uncased-squad': {
    id: 'qa-distilbert-uncased-squad',
    label: 'DistilBERT SQuAD (uncased)',
    provider: 'transformers',
    hfRepo: 'Xenova/distilbert-base-uncased-distilled-squad',
    sizeMB: 260,
    params: '67M',
    contextWindow: 512,
    task: 'qa',
    category: 'Comprehension',
    vramMB: 600,
    description: 'Ugyanaz kisbetűsítve; csupa kisbetűs szöveghez ezt válaszd.',
    evals: ['SQuAD v1.1'],
  },

  // -- Generation: összefoglalás, utasításkövetés ------------------------------
  'summarize-t5-small': {
    id: 'summarize-t5-small',
    label: 'T5-small (summarization)',
    provider: 'transformers',
    hfRepo: 'Xenova/t5-small',
    sizeMB: 230,
    params: '60M',
    contextWindow: 512,
    task: 'summarization',
    category: 'Generation',
    vramMB: 600,
    description: 'Összefoglalás, átfogalmazás prefixekkel ("summarize: ...").',
    evals: ['CNN/DailyMail', 'XSum'],
  },
  'instruct-flan-t5-small': {
    id: 'instruct-flan-t5-small',
    label: 'FLAN-T5-small (instruction)',
    provider: 'transformers',
    hfRepo: 'Xenova/flan-t5-small',
    sizeMB: 300,
    params: '80M',
    contextWindow: 512,
    task: 'text2text',
    category: 'Generation',
    vramMB: 700,
    description: 'Utasításra hangolt T5: összefoglal, válaszol, fordít — pici méretben.',
    evals: ['MMLU', 'BBH'],
  },

  // -- Translation (Helsinki-NLP OPUS-MT, CPU) ---------------------------------
  'translate-en-hu': {
    id: 'translate-en-hu',
    label: 'OPUS-MT en→hu',
    provider: 'transformers',
    hfRepo: 'Xenova/opus-mt-en-hu',
    sizeMB: 300,
    params: '74M',
    contextWindow: 512,
    task: 'translation',
    category: 'Translation',
    vramMB: 600,
    description: 'Angol→magyar fordítás, teljesen offline.',
    evals: ['WMT', 'Tatoeba'],
  },
  'translate-hu-en': {
    id: 'translate-hu-en',
    label: 'OPUS-MT hu→en',
    provider: 'transformers',
    hfRepo: 'Xenova/opus-mt-hu-en',
    sizeMB: 300,
    params: '74M',
    contextWindow: 512,
    task: 'translation',
    category: 'Translation',
    vramMB: 600,
    description: 'Magyar→angol fordítás, teljesen offline.',
    evals: ['WMT', 'Tatoeba'],
  },
  'translate-en-de': {
    id: 'translate-en-de',
    label: 'OPUS-MT en→de',
    provider: 'transformers',
    hfRepo: 'Xenova/opus-mt-en-de',
    sizeMB: 300,
    params: '74M',
    contextWindow: 512,
    task: 'translation',
    category: 'Translation',
    vramMB: 600,
    description: 'Angol→német fordítás, teljesen offline.',
    evals: ['WMT', 'Tatoeba'],
  },

  // -- Vision (transformers.js, CPU) -------------------------------------------
  'classify-resnet50': {
    id: 'classify-resnet50',
    label: 'ResNet-50 (ImageNet)',
    provider: 'transformers',
    hfRepo: 'Xenova/resnet-50',
    sizeMB: 100,
    params: '25M',
    contextWindow: 0,
    task: 'image-classification',
    category: 'Vision',
    vramMB: 500,
    description: '1000 kategóriás képfelismerés (ImageNet).',
    evals: ['ImageNet-1k'],
    score: '76.1% top-1',
  },
  'detect-yolos-tiny': {
    id: 'detect-yolos-tiny',
    label: 'YOLOS-tiny (detection)',
    provider: 'transformers',
    hfRepo: 'Xenova/yolos-tiny',
    sizeMB: 30,
    params: '6M',
    contextWindow: 0,
    task: 'object-detection',
    category: 'Vision',
    vramMB: 300,
    description: 'Apró valós idejű objektumdetektor; demóhoz, előszűréshez ideális.',
    evals: ['COCO'],
    score: '~29 box AP',
  },
  'detect-detr-r50': {
    id: 'detect-detr-r50',
    label: 'DETR-R50 (detection)',
    provider: 'transformers',
    hfRepo: 'Xenova/detr-resnet-50',
    sizeMB: 160,
    params: '42M',
    contextWindow: 0,
    task: 'object-detection',
    category: 'Vision',
    vramMB: 700,
    description: 'Pontosabb detektor, ha a YOLOS-tiny kevés.',
    evals: ['COCO'],
    score: '42.0 box AP',
  },
  'segment-segformer-b0': {
    id: 'segment-segformer-b0',
    label: 'SegFormer-B0 (ADE20K)',
    provider: 'transformers',
    hfRepo: 'Xenova/segformer-b0-finetuned-ade-512-512',
    sizeMB: 15,
    params: '4M',
    contextWindow: 0,
    task: 'segmentation',
    category: 'Vision',
    vramMB: 300,
    description: 'Szemantikus szegmentálás 150 osztállyal; a katalógus legkisebb látó modellje.',
    evals: ['ADE20K'],
    score: '37.4 mIoU',
  },

  // -- Document: OCR ------------------------------------------------------------
  'ocr-trocr-small': {
    id: 'ocr-trocr-small',
    label: 'TrOCR-small (printed)',
    provider: 'transformers',
    hfRepo: 'Xenova/trocr-small-printed',
    sizeMB: 250,
    params: '62M',
    contextWindow: 512,
    task: 'ocr',
    category: 'Document',
    vramMB: 600,
    description: 'Nyomtatott szöveg felolvasása képről; sorokra vágva működik legjobban.',
    evals: ['IAM', 'SROIE'],
  },

  // -- Speech (transformers.js, CPU) --------------------------------------------
  'whisper-tiny': {
    id: 'whisper-tiny',
    label: 'Whisper Tiny (transformers.js)',
    provider: 'transformers',
    hfRepo: 'Xenova/whisper-tiny',
    sizeMB: 150,
    params: '39M',
    contextWindow: 448,
    task: 'stt',
    category: 'Speech',
    vramMB: 500,
    description: 'Többnyelvű beszédfelismerés CPU-n; pontossága korlátozott.',
    evals: ['LibriSpeech'],
    score: '~8 WER',
  },
  'whisper-tiny-en': {
    id: 'whisper-tiny-en',
    label: 'Whisper Tiny.en (english-only)',
    provider: 'transformers',
    hfRepo: 'Xenova/whisper-tiny.en',
    sizeMB: 150,
    params: '39M',
    contextWindow: 448,
    task: 'stt',
    category: 'Speech',
    vramMB: 500,
    description: 'Csak angolul tud, cserébe pontosabb, mint a többnyelvű tiny.',
    evals: ['LibriSpeech'],
    score: '~7.5 WER (en)',
  },
  'whisper-base': {
    id: 'whisper-base',
    label: 'Whisper Base (transformers.js)',
    provider: 'transformers',
    hfRepo: 'Xenova/whisper-base',
    sizeMB: 250,
    params: '74M',
    contextWindow: 448,
    task: 'stt',
    category: 'Speech',
    vramMB: 700,
    description: 'Jobb pontosságú STT; még CPU-barát méret.',
    evals: ['LibriSpeech'],
    score: '~5.5 WER',
  },
  'tts-kokoro': {
    id: 'tts-kokoro',
    label: 'Kokoro TTS (placeholder)',
    provider: 'transformers',
    sizeMB: 300,
    params: '82M',
    contextWindow: 512,
    task: 'tts',
    category: 'Speech',
    vramMB: 800,
    description:
      'Placeholder: Kokoro 82M súlyok érkezésekor `hfRepo` + `modelUrl` pótlása.',
    evals: [],
  },
  speecht5: {
    id: 'speecht5',
    label: 'SpeechT5 TTS (transformers.js)',
    provider: 'transformers',
    hfRepo: 'Xenova/speecht5_tts',
    sizeMB: 300,
    params: '100M',
    contextWindow: 512,
    task: 'tts',
    category: 'Speech',
    vramMB: 800,
    description: 'Beszédszintézis CPU-n; beszélő-embeddinget igényel.',
    evals: ['LibriTTS'],
  },
};

/** Regiszter tömb formában (UI listákhoz, stabil sorrendben). */
export const MODEL_LIST: ModelInfo[] = Object.values(MODEL_REGISTRY);

/**
 * Modell metaadat lekérése id alapján.
 * @returns A modell infoja, vagy `undefined` ha ismeretlen.
 */
export function getModel(id: string): ModelInfo | undefined {
  return MODEL_REGISTRY[id];
}

/**
 * Modellek listázása, opcionálisan feladatra szűrve.
 */
export function listModels(task?: ModelTask): ModelInfo[] {
  if (task === undefined) return [...MODEL_LIST];
  return MODEL_LIST.filter((m) => m.task === task);
}

/**
 * Modellek listázása kategóriára szűrve (`MODEL_CATEGORIES` sorrendben).
 */
export function listModelsByCategory(category: ModelCategory): ModelInfo[] {
  return MODEL_LIST.filter((m) => m.category === category);
}

/** Igaz, ha az id szerepel a regiszterben. */
export function isKnownModel(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(MODEL_REGISTRY, id);
}
